### Send POST request with json body
POST http://127.0.0.1:5000/api/schedule
Content-Type: application/json
X-API-Key: {{X_API_KEY}}

{
  "content": "test message",
  "peer_id": "2000000005",
  "time_for_dispatch": "2022-10-09 15:54:17.090549",
  "payload": ""
}

### Get
GET http://127.0.0.1:5000/api/schedule?peer_id=2000000005
X-API-Key: {{X_API_KEY}}

### Get chat metadata
GET http://127.0.0.1:5000/api/chat?peer_id=2000000004
X-API-Key: {{X_API_KEY}}
